/* Auto-generated by scripts/fit_end_phase_lut.py — do not hand-edit.
 * End SurfaceNoise phase LUT on true y_offset phase:
 *   ef = frac(celly * 684.412 * persist + b)
 * Gate: OR4 = min OR max — score_min(min15,min14) ∨ score_max(max15,max14).
 * Features packed as kWeight[4]=[min15,max15,min14,max14]; separate intercepts.
 * Fitted on C++learning yoffset_corr.tsv env (per-side additive bin means).
 * Default threshold: known period 27/27 full recall (corr keep≈35%, filter≈65%).
 * Stricter: kThresholdKeep40 / kThresholdKeep258; looser: kThresholdKeep506.
 * Fidelity: relative to cubiomes End SurfaceNoise y_offset — not Official JAR.
 */
#pragma once

namespace end_phase_lut {
inline constexpr int kBins = 32;
inline constexpr int kFeatures = 4;
inline constexpr int kCelly = 18;
inline constexpr float kInterceptMin = 0.89038911F;
inline constexpr float kInterceptMax = 0.89038911F;
/* Legacy alias: mean of side intercepts (not used by OR gate). */
inline constexpr float kIntercept = 0.89038911F;
inline constexpr float kThreshold = 0.97045886F;
inline constexpr float kThresholdRecall = 0.97045886F;
inline constexpr float kThresholdKeep40 = 0.97086202F;
inline constexpr float kThresholdKeep258 = 0.97959868F;
inline constexpr float kThresholdKeep506 = 0.94240649F;
/* NVCC: constexpr arrays are host-only; device needs __constant__. */
#if defined(__CUDACC__)
__device__ __constant__ float kWeight[4][32] = {
#else
inline constexpr float kWeight[4][32] = {
#endif
    {
        -0.07243714F, -0.06858808F, -0.06960997F, -0.07395249F, -0.07625970F, -0.07877385F, -0.07375939F, -0.07505413F,
        -0.07363019F, -0.07020739F, -0.06225526F, -0.06636971F, -0.04694214F, -0.04213109F, -0.02419218F, -0.01215646F,
        0.00524746F, 0.01790731F, 0.03911098F, 0.05201739F, 0.07212864F, 0.08850304F, 0.09923484F, 0.10944523F,
        0.10073163F, 0.09600192F, 0.08676433F, 0.07592284F, 0.06306001F, 0.04349945F, 0.02768740F, 0.00959267F,
    },
    {
        -0.07350749F, -0.06609835F, -0.07376308F, -0.06898578F, -0.06738702F, -0.07178930F, -0.06116766F, -0.06869015F,
        -0.06435208F, -0.07511217F, -0.06962332F, -0.05743611F, -0.04947549F, -0.04586634F, -0.03411987F, -0.01632193F,
        -0.00523169F, 0.01724386F, 0.03303038F, 0.06411987F, 0.07308893F, 0.08232772F, 0.09676296F, 0.10508934F,
        0.10126309F, 0.09262392F, 0.08999919F, 0.07889034F, 0.06070477F, 0.04415381F, 0.02555812F, 0.00434880F,
    },
    {
        0.00265837F, -0.00255320F, 0.00211382F, 0.00191145F, -0.00596377F, -0.00489918F, -0.00343600F, 0.00776048F,
        0.00427799F, 0.00859143F, -0.00173346F, -0.00740038F, -0.00043600F, 0.00793111F, 0.00250264F, 0.00788027F,
        -0.00485185F, 0.00238404F, -0.00499450F, -0.00221604F, 0.00010271F, -0.00376070F, 0.00792088F, -0.00912882F,
        -0.00415459F, -0.00384399F, 0.00399940F, 0.00939964F, 0.00795162F, -0.00661906F, 0.00057075F, -0.01244761F,
    },
    {
        -0.00051272F, 0.01144198F, 0.00614033F, -0.01194043F, -0.01016429F, -0.00055992F, 0.01288929F, -0.00968614F,
        0.00200797F, 0.00255470F, 0.00963843F, -0.01670634F, -0.00522386F, -0.00525277F, 0.01493133F, -0.01049876F,
        0.00188365F, 0.00299620F, 0.01312167F, -0.01241870F, 0.00032822F, -0.00126547F, 0.01612064F, -0.01017194F,
        0.00636015F, -0.00149364F, 0.01470755F, -0.00860493F, -0.00687206F, -0.00225697F, 0.01617739F, -0.01753025F,
    },
};

inline constexpr float kIntercept15Min = 0.89038911F;
inline constexpr float kIntercept15Max = 0.89038911F;
inline constexpr float kIntercept15 = 0.89038911F;
inline constexpr float kThreshold15 = 0.98038829F;
#if defined(__CUDACC__)
__device__ __constant__ float kWeight15[2][32] = {
#else
inline constexpr float kWeight15[2][32] = {
#endif
    {
        -0.07243714F, -0.06858808F, -0.06960997F, -0.07395249F, -0.07625970F, -0.07877385F, -0.07375939F, -0.07505413F,
        -0.07363019F, -0.07020739F, -0.06225526F, -0.06636971F, -0.04694214F, -0.04213109F, -0.02419218F, -0.01215646F,
        0.00524746F, 0.01790731F, 0.03911098F, 0.05201739F, 0.07212864F, 0.08850304F, 0.09923484F, 0.10944523F,
        0.10073163F, 0.09600192F, 0.08676433F, 0.07592284F, 0.06306001F, 0.04349945F, 0.02768740F, 0.00959267F,
    },
    {
        -0.07350749F, -0.06609835F, -0.07376308F, -0.06898578F, -0.06738702F, -0.07178930F, -0.06116766F, -0.06869015F,
        -0.06435208F, -0.07511217F, -0.06962332F, -0.05743611F, -0.04947549F, -0.04586634F, -0.03411987F, -0.01632193F,
        -0.00523169F, 0.01724386F, 0.03303038F, 0.06411987F, 0.07308893F, 0.08232772F, 0.09676296F, 0.10508934F,
        0.10126309F, 0.09262392F, 0.08999919F, 0.07889034F, 0.06070477F, 0.04415381F, 0.02555812F, 0.00434880F,
    },
};
}  // namespace end_phase_lut

